### PR TITLE
Fix some PyLint errors

### PR DESCRIPTION
**Pull request by moreati**
Hope these changes aren't too presumptuous. This doesn't fix all the errors found, just the ones that seemed contentious to me. I also included some test suite updates. Here's the output before and after

### Before

```
************* Module mitogen.master
E:347,20: Undefined variable 'ast' (undefined-variable)
E:347,29: Undefined variable 'ast' (undefined-variable)
E:348,32: Undefined variable 'ast' (undefined-variable)
E:351,34: Undefined variable 'ast' (undefined-variable)
E:366,41: Undefined variable 'compiler' (undefined-variable)
E:367,32: Undefined variable 'compiler' (undefined-variable)
E:370,34: Undefined variable 'compiler' (undefined-variable)
E:395,11: Undefined variable 'ast' (undefined-variable)
E:566, 4: Method has no argument (no-method-argument)
************* Module mitogen.ssh
E: 87,40: Instance of 'Stream' has no 'auth_incorrect_msg' member (no-member)
************* Module mitogen.tcp
E: 24,18: Undefined variable 'Context' (undefined-variable)
E: 25,17: No value for argument 'remote_id' in constructor call (no-value-for-parameter)
E: 37, 4: Undefined variable 'LOG' (undefined-variable)
E: 39, 4: Undefined variable 'self' (undefined-variable)
E: 39,42: Undefined variable 'self' (undefined-variable)
E: 40, 4: Undefined variable 'self' (undefined-variable)
E: 40,43: Undefined variable 'self' (undefined-variable)
E: 41,17: Undefined variable 'self' (undefined-variable)
E: 42, 4: Undefined variable 'self' (undefined-variable)
E: 42,20: Undefined variable 'self' (undefined-variable)
************* Module mitogen.ansible.connection
E: 42,27: Module 'mitogen.master' has no 'connect' member (no-member)
E: 44,27: Module 'mitogen.ssh' has no 'connect' member (no-member)
E: 44,47: Undefined variable 'broker' (undefined-variable)
E: 50,18: Undefined variable 'AnsibleError' (undefined-variable)
************* Module mitogen.compat.pkgutil
E: 44,16: class already defined line 37 (function-redefined)
```

### After

```
************* Module mitogen.tcp
E: 26,18: No value for argument 'context_id' in constructor call (no-value-for-parameter)
E: 27,17: No value for argument 'remote_id' in constructor call (no-value-for-parameter)
E: 41, 4: Undefined variable 'self' (undefined-variable)
E: 41,42: Undefined variable 'self' (undefined-variable)
E: 42, 4: Undefined variable 'self' (undefined-variable)
E: 42,43: Undefined variable 'self' (undefined-variable)
E: 43,17: Undefined variable 'self' (undefined-variable)
E: 44, 4: Undefined variable 'self' (undefined-variable)
E: 44,20: Undefined variable 'self' (undefined-variable)
************* Module mitogen.compat.pkgutil
E: 44,16: class already defined line 37 (function-redefined)
```

### CODE REVIEW

**Comment by dw** [comment]
The only problem I spotted was the unconditional import of ast -- that module is new in Python 2.5, whereas the library is also targeting which requires the compiler module.

There is a lot of old crap checked in (like tcp.py -- it hasn't been touched in a very long time), and also in the tests dir. I just pulled in all my temporary hack scripts so I know to write equivalent tests for them.

If you fix the ast unconditional import I think this PR is otherwise fine. :)

**Comment by dw** [comment]
"targeting which requires" = "targeting 2.4 which requires"

**Comment by moreati** [comment]
> the library is also targeting 2.4 which requires the compiler module.

Ah right, I see now that you documented this in docs/index.rst.

Damn, I with the release of Ansible 2.4 I would finally seen the back of Python < 2.6 :smile:

**Comment by dw** [comment]
Thanks for this! Yeah I don't care what Ansible does w.r.t. compatiblity, I still see 2.4 around sometimes (as recently as last September). Will reevaluate when it comes to Python 3 support, but even then, support for older installs that actually exist today vs. hypothetical software that hardly anyone uses commercially is a major dealbreaker for me

**Pull request merged**
