### PR TITLE
 Aggregate code coverage data across all tox runs 

### LINKED ISSUE #529: Code coverage report only covers one Python version
`run_tests` generates a coverage report of the test suite. However it erases any previous coverage information each time it runs, this means the coverage report is incomplete for branches that depend on the Python version. Thus the coverage measured is lower than expected.

Patch incoming

### PR DESCRIPTION
**Pull request by moreati**
Fixes #529

### CODE REVIEW

**Comment by dw** [comment]
I think you might need to rebase -- sorry! Just merged something a minute ago

**Comment by dw** [comment]
Ooh, shiny "update branch" button. Have you tried that before?

**Comment by moreati** [comment]
Before

```
:~/src/mitogen [venv2] master+* 1± coverage report
Name                  Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------
mitogen/__init__.py      18     11      4      0    32%
mitogen/core.py        1565    467    436     52    67%
mitogen/debug.py         96     62     24      0    28%
mitogen/doas.py          60     15     25      7    61%
mitogen/docker.py        34      5     14      6    73%
mitogen/fakessh.py      199    152     42      0    20%
mitogen/fork.py          95     37     22      5    57%
mitogen/jail.py          24     24      4      0     0%
mitogen/kubectl.py       22      0      2      1    96%
mitogen/lxc.py           20      0      2      1    95%
mitogen/lxd.py           21      0      2      1    96%
mitogen/master.py       523     93    173     29    78%
mitogen/minify.py        78      5     38      6    91%
mitogen/parent.py       982    263    270     30    70%
mitogen/select.py        75      3     30      0    95%
mitogen/service.py      505    283    113      9    40%
mitogen/setns.py        131    131     34      0     0%
mitogen/ssh.py          166     11     77     13    90%
mitogen/su.py            62     18     25      7    59%
mitogen/sudo.py         106     18     34      7    78%
mitogen/unix.py          94     17      8      2    81%
mitogen/utils.py         83     13     30      6    80%
-------------------------------------------------------
TOTAL                  4959   1628   1409    182    64%
```

**Comment by moreati** [comment]
After

```
:~/src/mitogen [venv2] cover-us+* 1± coverage report
Name                  Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------
mitogen/__init__.py      18     11      4      0    32%
mitogen/core.py        1565    446    436     45    69%
mitogen/debug.py         96     62     24      0    28%
mitogen/doas.py          60     15     25      7    61%
mitogen/docker.py        34      5     14      6    73%
mitogen/fakessh.py      199    152     42      0    20%
mitogen/fork.py          95     37     22      4    58%
mitogen/jail.py          24     24      4      0     0%
mitogen/kubectl.py       22      0      2      1    96%
mitogen/lxc.py           20      0      2      1    95%
mitogen/lxd.py           21      0      2      1    96%
mitogen/master.py       523     79    173     20    83%
mitogen/minify.py        78      3     38      6    92%
mitogen/parent.py       982    250    270     30    71%
mitogen/select.py        75      3     30      0    95%
mitogen/service.py      505    281    113      8    40%
mitogen/setns.py        131    131     34      0     0%
mitogen/ssh.py          166      8     77     12    92%
mitogen/su.py            62     18     25      7    59%
mitogen/sudo.py         106     18     34      7    78%
mitogen/unix.py          94     17      8      2    81%
mitogen/utils.py         83      9     30      4    85%
-------------------------------------------------------
TOTAL                  4959   1569   1409    161    66%
```

**Comment by moreati** [comment]
> Ooh, shiny "update branch" button

Neat

**Comment by dw** [comment]
I wonder if there is some kind of badge we could use to pull this out into README

**Comment by moreati** [comment]
https://coveralls.io/ is the usual way to do it, we'd need to get the Travis builds using it

**Pull request merged**
