### PR TITLE
Fix DjangoMixin test imports for setuptools >= 50.0

### LINKED ISSUE #763: module_finder_test.DjangoMixin broken after setuptools dropped their vendored six
`module_finder_test.DjangoMixin` imports `pkg_resources._vendor.six`, which was removed from setuptools in https://github.com/pypa/setuptools/commit/45e0ea0ff10a64f315a5c65b6805327222e5b565. This is causing test failures on Azure, e.g. https://dev.azure.com/dw-mitogen/Mitogen/_build/results?buildId=1093&view=logs&j=7bdbcdc6-3d3e-568d-ccf8-9ddca1a9623a&t=b9c51d21-c8ff-5174-f249-be9415c61ba4

```
======================================================================
ERROR: module_finder_test (unittest2.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
ImportError: Failed to import test module: module_finder_test
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.6/site-packages/unittest2/loader.py", line 456, in _find_test_path
    module = self._get_module_from_name(name)
  File "/tmp/venv/lib/python3.6/site-packages/unittest2/loader.py", line 395, in _get_module_from_name
    __import__(name)
  File "/home/vsts/work/1/s/tests/module_finder_test.py", line 299, in <module>
    class DjangoMixin(object):
  File "/home/vsts/work/1/s/tests/module_finder_test.py", line 311, in DjangoMixin
    import pkg_resources._vendor.six
ModuleNotFoundError: No module named 'pkg_resources._vendor.six'
```

I am attempting a fix.

### PR DESCRIPTION
**Pull request by moreati**
Thanks for creating a PR! Here's a quick checklist to pay attention to:

- [x] Please add an entry to docs/changelog.rst

fixes #763

### CODE REVIEW

**Comment by s1113950** [comment]
@moreati could you change this PR to be based on the 0.2-release branch? After tests are fixed there and the part of https://github.com/dw/mitogen/pull/767 that applies to 0.2.10 is applied that branch can probably be tagged 0.2.10

**Comment by moreati** [comment]
> @moreati could you change this PR to be based on the 0.2-release branch? After tests are fixed there and the part of #767 that applies to 0.2.10 is applied that branch can probably be tagged 0.2.10

I'm not sure how to proceed with this.

Your changes for Ansible 2.10 (now in master, basis of 0.3.x releases)

1. set `'LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8`, to tackle the `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13` error that occurred during installation
2. pinned `pip==20.2.1`

My changes (in this PR) pin `pip==20.1.1`, as an alternative method of avoiding the `UnicodeDecodeError`.

Having the branches diverge further feels wrong.

**Comment by s1113950** [comment]
Ohh good point 🤔 maybe we close this then to avoid divergence? Or what if you keep everything but the pip pegging, so like `pyOpenSSL` and removing the `six` import?

**Comment by moreati** [comment]
> what if you keep everything but the pip pegging

I did that, intend to raise a second PR to backport this to release-0.2, once this is merged.

**Pull request merged**
